cache:
    - c:\cygwin-setup-cache

environment:
    matrix:
        - cygwin: https://cygwin.com/setup-x86_64.exe
        - cygwin: https://cygwin.com/setup-x86.exe

install:
    - ps: Invoke-WebRequest $env:cygwin -OutFile c:\cygwin-setup.exe
    - c:\cygwin-setup.exe --quiet-mode --no-shortcuts --no-startmenu --no-desktop --upgrade-also --only-site --site http://cygwin.mirror.constant.com/ --root c:\cygwin-root --local-package-dir c:\cygwin-setup-cache --packages gcc-g++,ninja,pkg-config,lv2-devel,libfftw3-devel,meson,zip

build_script:
    - cd C:\projects\noise-repellent
    - c:\cygwin-root\bin\sh -lc "chmod +x .ci/make-binaries-win"
    - c:\cygwin-root\bin\sh -lc ".ci/make-binaries-win"
    - ps: Push-AppveyorArtifact noise-repellent-win-$PLATFORM.zip