# There is a pre-installed cygwin: http://help.appveyor.com/discussions/suggestions/427-pre-install-cygwin
shallow_clone: true
cache:
    - c:\cygwin-setup-cache
environment:
    CYGWIN_NOWINPATH: yes
    matrix:
        - cygwin_url: https://cygwin.com/setup-x86_64.exe
        - cygwin_url: https://cygwin.com/setup-x86.exe
install:
    - ps: Invoke-WebRequest $env:cygwin_url -OutFile c:\cygwin-setup.exe
    - c:\cygwin-setup.exe --quiet-mode --no-shortcuts --no-startmenu --no-desktop --upgrade-also --only-site --site http://cygwin.mirror.constant.com/ --root c:\cygwin-root --local-package-dir c:\cygwin-setup-cache --packages gcc-g++,ninja,pkg-config,lv2-devel,libfftw3-devel,meson,zip
    - c:\cygwin-root\bin\sh -lc "uname -a"
    - c:\cygwin-root\bin\sh -lc "cat /proc/cpuinfo"
    - c:\cygwin-root\bin\sh -lc "cat /proc/meminfo"
    - c:\cygwin-root\bin\sh -lc "cygcheck -s -v > $APPVEYOR_BUILD_FOLDER/cygcheck.log 2>&1"
    - ps: Push-AppveyorArtifact cygcheck.log
build_script:
    - c:\cygwin-root\bin\sh -lc "ls -la"
    # - c:\cygwin-root\bin\sh -lc "chmod +x .ci/make-binaries-win"
    # - c:\cygwin-root\bin\sh -lc ".ci/make-binaries-win"
    # - ps: Push-AppveyorArtifact noise-repellent-win-$PLATFORM.zip