os:
  - linux
  
  sudo: required
  dist: trusty
  
  languages: c++
  
  services:
    - docker
  
  before_install:
    - docker build -t lucianoestebandato/noise-repellent-build:latest .
  
  script:
    - docker run -v `pwd`:/tmp/build --entrypoint "/bin/bash" lucianoestebandato/noise-repellent-build:latest -c "cd /tmp/build; CPUS=2 bash .travis/docker-script.sh"
  

deploy:
  provider: releases
  api_key:
    secure: nix7UnjIKYVxiDYSi08UDezDk+YWwy0OtsYlSkxMm7l5LfyMznw51dB4mX2H1QwqzTb0wLZLRdcTLkeF+z+j3FlcDCiOAhsZOHUJWESQVLSdG90Wa2QzI15d3jqjv9SQBVvbzlgXeTF78zVzUbkvyeFIYWKnLTo/3vUTBsRp+BXqR7tg0ovPa4CnR7SB/K2IDIskMedMo8oJhbedggwMt+22iYAb6sY0NpbpffD8ZtP4mrei5KLD4sadMaVzrXj9H6Gn5ukxglfUPHnEitI3iUVdTybTmpbtUUF90lSs8SdzGiBWAvkXnPAVP2QpKGmhAVyUGdWQ+1juTcLgzuSVz/ApsU0cRs5W88sDgm5ZCLnjA0B83X7QvCPMHrtOdFNLXgPoY8LVcEnzX+eNFVcDEw1VIArhe/8iQd/36G2kF5OuwNKqPVCGuWIPvpIePNwY2ieGV0P/dpPNgTtnsMw/JVsoGIA3TNFqn218Y1TFSZN7T+gU9nvpnfAa4qMfdX7gsWhKzSGgCRBJGVfLe1OgHko2gefNV9CLguaeax+t9J1D/Xx4X0tUwhh+mbkfMiPQ4/kd1j4e0msvs5xfYKPSwEXJG4JjWlN9s8TY3s55Rf3Rc7R8RlwRaTYZmeC1zmHUGyDz8k7KvOMj3uw2jVRMy3TTG2lWeJHe4HWRfoJsUoA=
  file: 
    - noise-repellent-$TRAVIS_TAG-linux.zip
    - noise-repellent-$TRAVIS_TAG-macos.zip
    - noise-repellent-$TRAVIS_TAG-win32.zip
    - noise-repellent-$TRAVIS_TAG-win64.zip
  skip_cleanup: true
  overwrite: true
  on:
    repo: lucianodato/noise-repellent
    tags: true
    branch: dockerbuild
